### ISSUE TITLE
Setup of promotion levels using YAML

### ISSUE THREAD

**Issue by dcoraboeuf** [nemerosa/ontrack-cli#15]
Given a YAML file like:

```yaml
- name: BRONZE
  validations:
    - unit-tests
    - lint
- name: SILVER
  promotions:
    - BRONZE
  validations:
    - deploy
```

support a command to setup the promotion levels like:

```bash
ontrack-cli promotion-level setup --project ... --branch ... --yaml <path to yaml>
```

It may not be possible to reuse the existing `setup` command.
